### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'multi_flow_network_id'

### ISSUE THREAD

**Issue by angyee** [ZTao-z/resnet-ssd#1]
$ sudo python3 trainCustom2012.py --dataset 'VOC' --basenet 'resnet50-19c8e357.pth' --cuda False  --batch_size 1 --dataset_root /home/new_ssd/resnet-ssd-master_custom/data/VOCdevkit
Traceback (most recent call last):
  File "trainCustom2012.py", line 280, in <module>
    train()
  File "trainCustom2012.py", line 109, in train
    ssd_net = build_ssd('train', cfg['min_dim'], cfg['num_classes'])
  File "/home/deepedge/project_getsenable_warehouse/new_ssd/resnet-ssd-master_custom/ssd_resnet.py", line 247, in build_ssd
    base_, extras_, head_ = multibox(resnet(),
  File "/home/deepedge/project_getsenable_warehouse/new_ssd/resnet-ssd-master_custom/ssd_resnet.py", line 147, in resnet
    multi_resnet_1 = resnet34(pretrained=False, multi_flow_network_id=0)
  File "/home/deepedge/project_getsenable_warehouse/new_ssd/resnet-ssd-master_custom/netModel/resnet.py", line 250, in resnet34
    **kwargs)
  File "/home/deepedge/project_getsenable_warehouse/new_ssd/resnet-ssd-master_custom/netModel/resnet.py", line 223, in _resnet
    model = ResNet(block, layers, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'multi_flow_network_id'

**Comment by ZTao-z** [comment]
非常抱歉，这个仓库的代码有点问题，可以看看https://github.com/ZTao-z/Detection-of-river-water-level-and-illegal-buildings-based-on-deep-learning这个仓库的代码，都是基于resnet-ssd模型

**Comment by ZTao-z** [comment]
非常抱歉，这个仓库的代码有点问题，可以看看https://github.com/ZTao-z/Detection-of-river-water-level-and-illegal-buildings-based-on-deep-learning 这个仓库的代码，都是基于resnet-ssd模型
